services:
  jenkins:
    image: sogis/jenkins:lts
    environment:
      TZ: Europe/Zurich
    ports:
      - "8081:8080"
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
