name: Docker Jenkins CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    name: Build docker image Jenkins
    runs-on: ubuntu-22.04
    env:
      JENKINS_VERSION: lts

    steps:

    - name: Set up QEMU for amd64 and arm64
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: sogis/jenkins
        labels: |
          org.opencontainers.image.title=jenkins
          org.opencontainers.image.version=${{ env.JENKINS_VERSION }}
          org.opencontainers.image.base.name=jenkins:lts
        tags: |
          type=raw,value=${{ env.JENKINS_VERSION }},enable=true,priority=200

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

    - name: Multi-platform build and push
      uses: docker/build-push-action@v2
      with:
        #platforms: linux/amd64,linux/arm64
        platforms: linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        pull: true
        push: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}
